<?php

// Auto-generated by OpenAPI Generator. Do not edit manually.

namespace OpenAPI\FraudIntel\Client\Model;

use ArrayAccess;
use OpenAPI\FraudIntel\Client\ObjectSerializer;

class AnalyzeFraud200ResponseSourcesGeoSignals implements \JsonSerializable, ArrayAccess, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'analyzeFraud_200_response_sources_geo_signals';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'ip_country' => 'string',
        'phone_country' => 'string',
        'email_domain_country' => 'string',
        'session_country' => 'string',
        'declared_country' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'ip_country' => null,
        'phone_country' => null,
        'email_domain_country' => null,
        'session_country' => null,
        'declared_country' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'ip_country' => true,
        'phone_country' => true,
        'email_domain_country' => true,
        'session_country' => true,
        'declared_country' => true,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param  bool[]  $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ip_country' => 'ipCountry',
        'phone_country' => 'phoneCountry',
        'email_domain_country' => 'emailDomainCountry',
        'session_country' => 'sessionCountry',
        'declared_country' => 'declaredCountry',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ip_country' => 'setIpCountry',
        'phone_country' => 'setPhoneCountry',
        'email_domain_country' => 'setEmailDomainCountry',
        'session_country' => 'setSessionCountry',
        'declared_country' => 'setDeclaredCountry',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ip_country' => 'getIpCountry',
        'phone_country' => 'getPhoneCountry',
        'email_domain_country' => 'getEmailDomainCountry',
        'session_country' => 'getSessionCountry',
        'declared_country' => 'getDeclaredCountry',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param  mixed[]|null  $data  Associated array of property values
     *                              initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('ip_country', $data ?? [], null);
        $this->setIfExists('phone_country', $data ?? [], null);
        $this->setIfExists('email_domain_country', $data ?? [], null);
        $this->setIfExists('session_country', $data ?? [], null);
        $this->setIfExists('declared_country', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param  mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets ip_country
     *
     * @return string|null
     */
    public function getIpCountry()
    {
        return $this->container['ip_country'];
    }

    /**
     * Sets ip_country
     *
     * @param  string|null  $ip_country  Country from IP geolocation.
     * @return self
     */
    public function setIpCountry($ip_country)
    {
        if (is_null($ip_country)) {
            array_push($this->openAPINullablesSetToNull, 'ip_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ip_country', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ip_country'] = $ip_country;

        return $this;
    }

    /**
     * Gets phone_country
     *
     * @return string|null
     */
    public function getPhoneCountry()
    {
        return $this->container['phone_country'];
    }

    /**
     * Sets phone_country
     *
     * @param  string|null  $phone_country  Country from phone number registration data.
     * @return self
     */
    public function setPhoneCountry($phone_country)
    {
        if (is_null($phone_country)) {
            array_push($this->openAPINullablesSetToNull, 'phone_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone_country', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone_country'] = $phone_country;

        return $this;
    }

    /**
     * Gets email_domain_country
     *
     * @return string|null
     */
    public function getEmailDomainCountry()
    {
        return $this->container['email_domain_country'];
    }

    /**
     * Sets email_domain_country
     *
     * @param  string|null  $email_domain_country  Country inferred from email domain registration.
     * @return self
     */
    public function setEmailDomainCountry($email_domain_country)
    {
        if (is_null($email_domain_country)) {
            array_push($this->openAPINullablesSetToNull, 'email_domain_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email_domain_country', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email_domain_country'] = $email_domain_country;

        return $this;
    }

    /**
     * Gets session_country
     *
     * @return string|null
     */
    public function getSessionCountry()
    {
        return $this->container['session_country'];
    }

    /**
     * Sets session_country
     *
     * @param  string|null  $session_country  Country from the session source IP (behavioral data).
     * @return self
     */
    public function setSessionCountry($session_country)
    {
        if (is_null($session_country)) {
            array_push($this->openAPINullablesSetToNull, 'session_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('session_country', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['session_country'] = $session_country;

        return $this;
    }

    /**
     * Gets declared_country
     *
     * @return string|null
     */
    public function getDeclaredCountry()
    {
        return $this->container['declared_country'];
    }

    /**
     * Sets declared_country
     *
     * @param  string|null  $declared_country  Country from the `country` request field (ISO 3166-1 alpha-2).
     * @return self
     */
    public function setDeclaredCountry($declared_country)
    {
        if (is_null($declared_country)) {
            array_push($this->openAPINullablesSetToNull, 'declared_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('declared_country', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['declared_country'] = $declared_country;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  int|string  $offset  Offset
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  int|null  $offset  Offset
     * @param  mixed  $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
