<?php

// Auto-generated by OpenAPI Generator. Do not edit manually.

namespace OpenAPI\FraudIntel\Client\Model;

use ArrayAccess;
use OpenAPI\FraudIntel\Client\ObjectSerializer;

class AnalyzeFraud200ResponseSourcesSession implements \JsonSerializable, ArrayAccess, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'analyzeFraud_200_response_sources_session';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'client_id' => 'string',
        'session_id' => 'string',
        'fuuid' => 'string',
        'token_age' => 'float',
        'token_valid' => 'bool',
        'detections' => '\OpenAPI\FraudIntel\Client\Model\FraudAnalyzeSessionDetectionsInner[]',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'client_id' => null,
        'session_id' => null,
        'fuuid' => null,
        'token_age' => null,
        'token_valid' => null,
        'detections' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'client_id' => false,
        'session_id' => false,
        'fuuid' => false,
        'token_age' => false,
        'token_valid' => false,
        'detections' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param  bool[]  $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'client_id' => 'clientId',
        'session_id' => 'sessionId',
        'fuuid' => 'fuuid',
        'token_age' => 'tokenAge',
        'token_valid' => 'tokenValid',
        'detections' => 'detections',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'client_id' => 'setClientId',
        'session_id' => 'setSessionId',
        'fuuid' => 'setFuuid',
        'token_age' => 'setTokenAge',
        'token_valid' => 'setTokenValid',
        'detections' => 'setDetections',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'client_id' => 'getClientId',
        'session_id' => 'getSessionId',
        'fuuid' => 'getFuuid',
        'token_age' => 'getTokenAge',
        'token_valid' => 'getTokenValid',
        'detections' => 'getDetections',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param  mixed[]|null  $data  Associated array of property values
     *                              initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('client_id', $data ?? [], null);
        $this->setIfExists('session_id', $data ?? [], null);
        $this->setIfExists('fuuid', $data ?? [], null);
        $this->setIfExists('token_age', $data ?? [], null);
        $this->setIfExists('token_valid', $data ?? [], null);
        $this->setIfExists('detections', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param  mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets client_id
     *
     * @return string|null
     */
    public function getClientId()
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     *
     * @param  string|null  $client_id  Persistent device fingerprint identifier.
     * @return self
     */
    public function setClientId($client_id)
    {
        if (is_null($client_id)) {
            throw new \InvalidArgumentException('non-nullable client_id cannot be null');
        }
        $this->container['client_id'] = $client_id;

        return $this;
    }

    /**
     * Gets session_id
     *
     * @return string|null
     */
    public function getSessionId()
    {
        return $this->container['session_id'];
    }

    /**
     * Sets session_id
     *
     * @param  string|null  $session_id  Session-scoped identifier for the current browser session.
     * @return self
     */
    public function setSessionId($session_id)
    {
        if (is_null($session_id)) {
            throw new \InvalidArgumentException('non-nullable session_id cannot be null');
        }
        $this->container['session_id'] = $session_id;

        return $this;
    }

    /**
     * Gets fuuid
     *
     * @return string|null
     */
    public function getFuuid()
    {
        return $this->container['fuuid'];
    }

    /**
     * Sets fuuid
     *
     * @param  string|null  $fuuid  UUID of the form as stored in the session record (raw field name from the SDK).
     * @return self
     */
    public function setFuuid($fuuid)
    {
        if (is_null($fuuid)) {
            throw new \InvalidArgumentException('non-nullable fuuid cannot be null');
        }
        $this->container['fuuid'] = $fuuid;

        return $this;
    }

    /**
     * Gets token_age
     *
     * @return float|null
     */
    public function getTokenAge()
    {
        return $this->container['token_age'];
    }

    /**
     * Sets token_age
     *
     * @param  float|null  $token_age  Age of the SDK-issued token in seconds at the time of submission.
     * @return self
     */
    public function setTokenAge($token_age)
    {
        if (is_null($token_age)) {
            throw new \InvalidArgumentException('non-nullable token_age cannot be null');
        }
        $this->container['token_age'] = $token_age;

        return $this;
    }

    /**
     * Gets token_valid
     *
     * @return bool|null
     */
    public function getTokenValid()
    {
        return $this->container['token_valid'];
    }

    /**
     * Sets token_valid
     *
     * @param  bool|null  $token_valid  Whether the token passed cryptographic verification.
     * @return self
     */
    public function setTokenValid($token_valid)
    {
        if (is_null($token_valid)) {
            throw new \InvalidArgumentException('non-nullable token_valid cannot be null');
        }
        $this->container['token_valid'] = $token_valid;

        return $this;
    }

    /**
     * Gets detections
     *
     * @return \OpenAPI\FraudIntel\Client\Model\FraudAnalyzeSessionDetectionsInner[]|null
     */
    public function getDetections()
    {
        return $this->container['detections'];
    }

    /**
     * Sets detections
     *
     * @param  \OpenAPI\FraudIntel\Client\Model\FraudAnalyzeSessionDetectionsInner[]|null  $detections  Behavioral detection results aggregated from the session and its associated event records, deduplicated by name. Each element is a name/value pair. Example detection names: hpot (honeypot triggered),…
     * @return self
     */
    public function setDetections($detections)
    {
        if (is_null($detections)) {
            throw new \InvalidArgumentException('non-nullable detections cannot be null');
        }
        $this->container['detections'] = $detections;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  int|string  $offset  Offset
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  int|null  $offset  Offset
     * @param  mixed  $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
