<?php

// Auto-generated by OpenAPI Generator. Do not edit manually.

namespace OpenAPI\FraudIntel\Client\Model;

use ArrayAccess;
use OpenAPI\FraudIntel\Client\ObjectSerializer;

class EmailDomain implements \JsonSerializable, ArrayAccess, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'EmailDomain';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'name' => 'string',
        'enrichment_available' => 'bool',
        'creation_date' => 'string',
        'expiration_date' => 'string',
        'updated_date' => 'string',
        'age_years' => 'int',
        'registrar' => 'string',
        'is_block_listed' => 'bool',
        'mta_sts_status' => 'string',
        'bimi_status' => 'string',
        'has_vmc' => 'bool',
        'a_record_valid' => 'bool',
        'a_record_reverse_host' => 'string',
        'ssl_valid' => 'bool',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'name' => null,
        'enrichment_available' => null,
        'creation_date' => null,
        'expiration_date' => null,
        'updated_date' => null,
        'age_years' => null,
        'registrar' => null,
        'is_block_listed' => null,
        'mta_sts_status' => null,
        'bimi_status' => null,
        'has_vmc' => null,
        'a_record_valid' => null,
        'a_record_reverse_host' => null,
        'ssl_valid' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'name' => false,
        'enrichment_available' => false,
        'creation_date' => false,
        'expiration_date' => false,
        'updated_date' => false,
        'age_years' => false,
        'registrar' => false,
        'is_block_listed' => false,
        'mta_sts_status' => false,
        'bimi_status' => false,
        'has_vmc' => false,
        'a_record_valid' => false,
        'a_record_reverse_host' => false,
        'ssl_valid' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param  bool[]  $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'enrichment_available' => 'enrichmentAvailable',
        'creation_date' => 'creationDate',
        'expiration_date' => 'expirationDate',
        'updated_date' => 'updatedDate',
        'age_years' => 'ageYears',
        'registrar' => 'registrar',
        'is_block_listed' => 'isBlockListed',
        'mta_sts_status' => 'mtaStsStatus',
        'bimi_status' => 'bimiStatus',
        'has_vmc' => 'hasVMC',
        'a_record_valid' => 'aRecordValid',
        'a_record_reverse_host' => 'aRecordReverseHost',
        'ssl_valid' => 'sslValid',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'enrichment_available' => 'setEnrichmentAvailable',
        'creation_date' => 'setCreationDate',
        'expiration_date' => 'setExpirationDate',
        'updated_date' => 'setUpdatedDate',
        'age_years' => 'setAgeYears',
        'registrar' => 'setRegistrar',
        'is_block_listed' => 'setIsBlockListed',
        'mta_sts_status' => 'setMtaStsStatus',
        'bimi_status' => 'setBimiStatus',
        'has_vmc' => 'setHasVmc',
        'a_record_valid' => 'setARecordValid',
        'a_record_reverse_host' => 'setARecordReverseHost',
        'ssl_valid' => 'setSslValid',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'enrichment_available' => 'getEnrichmentAvailable',
        'creation_date' => 'getCreationDate',
        'expiration_date' => 'getExpirationDate',
        'updated_date' => 'getUpdatedDate',
        'age_years' => 'getAgeYears',
        'registrar' => 'getRegistrar',
        'is_block_listed' => 'getIsBlockListed',
        'mta_sts_status' => 'getMtaStsStatus',
        'bimi_status' => 'getBimiStatus',
        'has_vmc' => 'getHasVmc',
        'a_record_valid' => 'getARecordValid',
        'a_record_reverse_host' => 'getARecordReverseHost',
        'ssl_valid' => 'getSslValid',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param  mixed[]|null  $data  Associated array of property values
     *                              initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('enrichment_available', $data ?? [], null);
        $this->setIfExists('creation_date', $data ?? [], null);
        $this->setIfExists('expiration_date', $data ?? [], null);
        $this->setIfExists('updated_date', $data ?? [], null);
        $this->setIfExists('age_years', $data ?? [], null);
        $this->setIfExists('registrar', $data ?? [], null);
        $this->setIfExists('is_block_listed', $data ?? [], null);
        $this->setIfExists('mta_sts_status', $data ?? [], null);
        $this->setIfExists('bimi_status', $data ?? [], null);
        $this->setIfExists('has_vmc', $data ?? [], null);
        $this->setIfExists('a_record_valid', $data ?? [], null);
        $this->setIfExists('a_record_reverse_host', $data ?? [], null);
        $this->setIfExists('ssl_valid', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param  mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['enrichment_available'] === null) {
            $invalidProperties[] = "'enrichment_available' can't be null";
        }
        if ($this->container['creation_date'] === null) {
            $invalidProperties[] = "'creation_date' can't be null";
        }
        if ($this->container['expiration_date'] === null) {
            $invalidProperties[] = "'expiration_date' can't be null";
        }
        if ($this->container['updated_date'] === null) {
            $invalidProperties[] = "'updated_date' can't be null";
        }
        if ($this->container['age_years'] === null) {
            $invalidProperties[] = "'age_years' can't be null";
        }
        if ($this->container['registrar'] === null) {
            $invalidProperties[] = "'registrar' can't be null";
        }
        if ($this->container['is_block_listed'] === null) {
            $invalidProperties[] = "'is_block_listed' can't be null";
        }
        if ($this->container['mta_sts_status'] === null) {
            $invalidProperties[] = "'mta_sts_status' can't be null";
        }
        if ($this->container['bimi_status'] === null) {
            $invalidProperties[] = "'bimi_status' can't be null";
        }
        if ($this->container['has_vmc'] === null) {
            $invalidProperties[] = "'has_vmc' can't be null";
        }
        if ($this->container['a_record_valid'] === null) {
            $invalidProperties[] = "'a_record_valid' can't be null";
        }
        if ($this->container['a_record_reverse_host'] === null) {
            $invalidProperties[] = "'a_record_reverse_host' can't be null";
        }
        if ($this->container['ssl_valid'] === null) {
            $invalidProperties[] = "'ssl_valid' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param  string  $name  Fully qualified domain name associated with the email. Default: empty string. Example: \"company.com\".
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets enrichment_available
     *
     * @return bool
     */
    public function getEnrichmentAvailable()
    {
        return $this->container['enrichment_available'];
    }

    /**
     * Sets enrichment_available
     *
     * @param  bool  $enrichment_available  Indicates whether enrichment data was available at analysis time.
     * @return self
     */
    public function setEnrichmentAvailable($enrichment_available)
    {
        if (is_null($enrichment_available)) {
            throw new \InvalidArgumentException('non-nullable enrichment_available cannot be null');
        }
        $this->container['enrichment_available'] = $enrichment_available;

        return $this;
    }

    /**
     * Gets creation_date
     *
     * @return string
     */
    public function getCreationDate()
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param  string  $creation_date  Domain creation timestamp (ISO 8601). Returns an empty string when enrichment data is unavailable. Format: date-time. Example: \"2014-05-12T00:00:00Z\".
     * @return self
     */
    public function setCreationDate($creation_date)
    {
        if (is_null($creation_date)) {
            throw new \InvalidArgumentException('non-nullable creation_date cannot be null');
        }
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets expiration_date
     *
     * @return string
     */
    public function getExpirationDate()
    {
        return $this->container['expiration_date'];
    }

    /**
     * Sets expiration_date
     *
     * @param  string  $expiration_date  Domain expiration timestamp (ISO 8601). Returns an empty string when enrichment data is unavailable. Format: date-time. Example: \"2026-05-11T23:59:59Z\".
     * @return self
     */
    public function setExpirationDate($expiration_date)
    {
        if (is_null($expiration_date)) {
            throw new \InvalidArgumentException('non-nullable expiration_date cannot be null');
        }
        $this->container['expiration_date'] = $expiration_date;

        return $this;
    }

    /**
     * Gets updated_date
     *
     * @return string
     */
    public function getUpdatedDate()
    {
        return $this->container['updated_date'];
    }

    /**
     * Sets updated_date
     *
     * @param  string  $updated_date  Last WHOIS update timestamp (ISO 8601). Returns an empty string when enrichment data is unavailable. Format: date-time. Example: \"2024-11-01T08:30:00Z\".
     * @return self
     */
    public function setUpdatedDate($updated_date)
    {
        if (is_null($updated_date)) {
            throw new \InvalidArgumentException('non-nullable updated_date cannot be null');
        }
        $this->container['updated_date'] = $updated_date;

        return $this;
    }

    /**
     * Gets age_years
     *
     * @return int
     */
    public function getAgeYears()
    {
        return $this->container['age_years'];
    }

    /**
     * Sets age_years
     *
     * @param  int  $age_years  Domain age in whole years based on stored enrichment data. Returns 0 for domains younger than one year. Default: 0. Example: 11.
     * @return self
     */
    public function setAgeYears($age_years)
    {
        if (is_null($age_years)) {
            throw new \InvalidArgumentException('non-nullable age_years cannot be null');
        }
        $this->container['age_years'] = $age_years;

        return $this;
    }

    /**
     * Gets registrar
     *
     * @return string
     */
    public function getRegistrar()
    {
        return $this->container['registrar'];
    }

    /**
     * Sets registrar
     *
     * @param  string  $registrar  Registrar recorded for the domain. Default: empty string. Example: \"Namecheap, Inc.\".
     * @return self
     */
    public function setRegistrar($registrar)
    {
        if (is_null($registrar)) {
            throw new \InvalidArgumentException('non-nullable registrar cannot be null');
        }
        $this->container['registrar'] = $registrar;

        return $this;
    }

    /**
     * Gets is_block_listed
     *
     * @return bool
     */
    public function getIsBlockListed()
    {
        return $this->container['is_block_listed'];
    }

    /**
     * Sets is_block_listed
     *
     * @param  bool  $is_block_listed  Indicates whether the domain appears in monitored blocklists. Default: false. Example: false.
     * @return self
     */
    public function setIsBlockListed($is_block_listed)
    {
        if (is_null($is_block_listed)) {
            throw new \InvalidArgumentException('non-nullable is_block_listed cannot be null');
        }
        $this->container['is_block_listed'] = $is_block_listed;

        return $this;
    }

    /**
     * Gets mta_sts_status
     *
     * @return string
     */
    public function getMtaStsStatus()
    {
        return $this->container['mta_sts_status'];
    }

    /**
     * Sets mta_sts_status
     *
     * @param  string  $mta_sts_status  Status of the domain's MTA-STS configuration. Allowed values: `present`, `invalid`, `absent`, `unknown`. Default: `unknown`. Example: `present`.
     * @return self
     */
    public function setMtaStsStatus($mta_sts_status)
    {
        if (is_null($mta_sts_status)) {
            throw new \InvalidArgumentException('non-nullable mta_sts_status cannot be null');
        }
        $this->container['mta_sts_status'] = $mta_sts_status;

        return $this;
    }

    /**
     * Gets bimi_status
     *
     * @return string
     */
    public function getBimiStatus()
    {
        return $this->container['bimi_status'];
    }

    /**
     * Sets bimi_status
     *
     * @param  string  $bimi_status  BIMI (Brand Indicators for Message Identification) status. Allowed values: `present`, `present-no-vmc`, `invalid`, `absent`, `unknown`. Default: `unknown`. Example: `present-no-vmc`.
     * @return self
     */
    public function setBimiStatus($bimi_status)
    {
        if (is_null($bimi_status)) {
            throw new \InvalidArgumentException('non-nullable bimi_status cannot be null');
        }
        $this->container['bimi_status'] = $bimi_status;

        return $this;
    }

    /**
     * Gets has_vmc
     *
     * @return bool
     */
    public function getHasVmc()
    {
        return $this->container['has_vmc'];
    }

    /**
     * Sets has_vmc
     *
     * @param  bool  $has_vmc  Indicates whether a Verified Mark Certificate is associated with the domain. Default: false. Example: false.
     * @return self
     */
    public function setHasVmc($has_vmc)
    {
        if (is_null($has_vmc)) {
            throw new \InvalidArgumentException('non-nullable has_vmc cannot be null');
        }
        $this->container['has_vmc'] = $has_vmc;

        return $this;
    }

    /**
     * Gets a_record_valid
     *
     * @return bool
     */
    public function getARecordValid()
    {
        return $this->container['a_record_valid'];
    }

    /**
     * Sets a_record_valid
     *
     * @param  bool  $a_record_valid  Indicates whether the domain has valid A records. Default: false. Example: true.
     * @return self
     */
    public function setARecordValid($a_record_valid)
    {
        if (is_null($a_record_valid)) {
            throw new \InvalidArgumentException('non-nullable a_record_valid cannot be null');
        }
        $this->container['a_record_valid'] = $a_record_valid;

        return $this;
    }

    /**
     * Gets a_record_reverse_host
     *
     * @return string
     */
    public function getARecordReverseHost()
    {
        return $this->container['a_record_reverse_host'];
    }

    /**
     * Sets a_record_reverse_host
     *
     * @param  string  $a_record_reverse_host  Reverse hostname observed for the A record when available. Empty string when no reverse mapping is returned. Default: empty string. Example: \"reverse.company.com\".
     * @return self
     */
    public function setARecordReverseHost($a_record_reverse_host)
    {
        if (is_null($a_record_reverse_host)) {
            throw new \InvalidArgumentException('non-nullable a_record_reverse_host cannot be null');
        }
        $this->container['a_record_reverse_host'] = $a_record_reverse_host;

        return $this;
    }

    /**
     * Gets ssl_valid
     *
     * @return bool
     */
    public function getSslValid()
    {
        return $this->container['ssl_valid'];
    }

    /**
     * Sets ssl_valid
     *
     * @param  bool  $ssl_valid  Indicates whether the domain serves a valid SSL certificate on common endpoints. Default: false. Example: true.
     * @return self
     */
    public function setSslValid($ssl_valid)
    {
        if (is_null($ssl_valid)) {
            throw new \InvalidArgumentException('non-nullable ssl_valid cannot be null');
        }
        $this->container['ssl_valid'] = $ssl_valid;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  int|string  $offset  Offset
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  int|null  $offset  Offset
     * @param  mixed  $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
