<?php

// Auto-generated by OpenAPI Generator. Do not edit manually.

namespace OpenAPI\FraudIntel\Client\Model;

use ArrayAccess;
use OpenAPI\FraudIntel\Client\ObjectSerializer;

class FraudVelocityWindow implements \JsonSerializable, ArrayAccess, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'FraudVelocityWindow';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'last60s' => 'int',
        'last300s' => 'int',
        'last3600s' => 'int',
        'last86400s' => 'int',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'last60s' => null,
        'last300s' => null,
        'last3600s' => null,
        'last86400s' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'last60s' => false,
        'last300s' => false,
        'last3600s' => false,
        'last86400s' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param  bool[]  $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'last60s' => 'last60s',
        'last300s' => 'last300s',
        'last3600s' => 'last3600s',
        'last86400s' => 'last86400s',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'last60s' => 'setLast60s',
        'last300s' => 'setLast300s',
        'last3600s' => 'setLast3600s',
        'last86400s' => 'setLast86400s',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'last60s' => 'getLast60s',
        'last300s' => 'getLast300s',
        'last3600s' => 'getLast3600s',
        'last86400s' => 'getLast86400s',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param  mixed[]|null  $data  Associated array of property values
     *                              initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('last60s', $data ?? [], null);
        $this->setIfExists('last300s', $data ?? [], null);
        $this->setIfExists('last3600s', $data ?? [], null);
        $this->setIfExists('last86400s', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param  mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets last60s
     *
     * @return int|null
     */
    public function getLast60s()
    {
        return $this->container['last60s'];
    }

    /**
     * Sets last60s
     *
     * @param  int|null  $last60s  Number of submissions seen for this identifier in the last 60 seconds.
     * @return self
     */
    public function setLast60s($last60s)
    {
        if (is_null($last60s)) {
            throw new \InvalidArgumentException('non-nullable last60s cannot be null');
        }
        $this->container['last60s'] = $last60s;

        return $this;
    }

    /**
     * Gets last300s
     *
     * @return int|null
     */
    public function getLast300s()
    {
        return $this->container['last300s'];
    }

    /**
     * Sets last300s
     *
     * @param  int|null  $last300s  Number of submissions seen for this identifier in the last 5 minutes.
     * @return self
     */
    public function setLast300s($last300s)
    {
        if (is_null($last300s)) {
            throw new \InvalidArgumentException('non-nullable last300s cannot be null');
        }
        $this->container['last300s'] = $last300s;

        return $this;
    }

    /**
     * Gets last3600s
     *
     * @return int|null
     */
    public function getLast3600s()
    {
        return $this->container['last3600s'];
    }

    /**
     * Sets last3600s
     *
     * @param  int|null  $last3600s  Number of submissions seen for this identifier in the last hour.
     * @return self
     */
    public function setLast3600s($last3600s)
    {
        if (is_null($last3600s)) {
            throw new \InvalidArgumentException('non-nullable last3600s cannot be null');
        }
        $this->container['last3600s'] = $last3600s;

        return $this;
    }

    /**
     * Gets last86400s
     *
     * @return int|null
     */
    public function getLast86400s()
    {
        return $this->container['last86400s'];
    }

    /**
     * Sets last86400s
     *
     * @param  int|null  $last86400s  Number of submissions seen for this identifier in the last 24 hours.
     * @return self
     */
    public function setLast86400s($last86400s)
    {
        if (is_null($last86400s)) {
            throw new \InvalidArgumentException('non-nullable last86400s cannot be null');
        }
        $this->container['last86400s'] = $last86400s;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  int|string  $offset  Offset
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  int|null  $offset  Offset
     * @param  mixed  $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
