<?php
// Auto-generated by OpenAPI Generator. Do not edit manually.

namespace OpenAPI\FraudIntel\Client\Model;

use \ArrayAccess;
use \OpenAPI\FraudIntel\Client\ObjectSerializer;

class Whois implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Whois';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'rir' => 'string',
        'asn' => '\OpenAPI\FraudIntel\Client\Model\Asn',
        'organization' => '\OpenAPI\FraudIntel\Client\Model\Organization',
        'abuse_contact' => '\OpenAPI\FraudIntel\Client\Model\AbuseContact',
        'admin_contact' => '\OpenAPI\FraudIntel\Client\Model\AdminContact',
        'tech_contact' => '\OpenAPI\FraudIntel\Client\Model\TechContact'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'rir' => null,
        'asn' => null,
        'organization' => null,
        'abuse_contact' => null,
        'admin_contact' => null,
        'tech_contact' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'rir' => false,
        'asn' => false,
        'organization' => false,
        'abuse_contact' => false,
        'admin_contact' => false,
        'tech_contact' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rir' => 'rir',
        'asn' => 'asn',
        'organization' => 'organization',
        'abuse_contact' => 'abuseContact',
        'admin_contact' => 'adminContact',
        'tech_contact' => 'techContact'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rir' => 'setRir',
        'asn' => 'setAsn',
        'organization' => 'setOrganization',
        'abuse_contact' => 'setAbuseContact',
        'admin_contact' => 'setAdminContact',
        'tech_contact' => 'setTechContact'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rir' => 'getRir',
        'asn' => 'getAsn',
        'organization' => 'getOrganization',
        'abuse_contact' => 'getAbuseContact',
        'admin_contact' => 'getAdminContact',
        'tech_contact' => 'getTechContact'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('rir', $data ?? [], null);
        $this->setIfExists('asn', $data ?? [], null);
        $this->setIfExists('organization', $data ?? [], null);
        $this->setIfExists('abuse_contact', $data ?? [], null);
        $this->setIfExists('admin_contact', $data ?? [], null);
        $this->setIfExists('tech_contact', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets rir
     *
     * @return string|null
     */
    public function getRir()
    {
        return $this->container['rir'];
    }

    /**
     * Sets rir
     *
     * @param string|null $rir Regional Internet Registry managing the IP.
     *
     * @return self
     */
    public function setRir($rir)
    {
        if (is_null($rir)) {
            throw new \InvalidArgumentException('non-nullable rir cannot be null');
        }
        $this->container['rir'] = $rir;

        return $this;
    }

    /**
     * Gets asn
     *
     * @return \OpenAPI\FraudIntel\Client\Model\Asn|null
     */
    public function getAsn()
    {
        return $this->container['asn'];
    }

    /**
     * Sets asn
     *
     * @param \OpenAPI\FraudIntel\Client\Model\Asn|null $asn asn
     *
     * @return self
     */
    public function setAsn($asn)
    {
        if (is_null($asn)) {
            throw new \InvalidArgumentException('non-nullable asn cannot be null');
        }
        $this->container['asn'] = $asn;

        return $this;
    }

    /**
     * Gets organization
     *
     * @return \OpenAPI\FraudIntel\Client\Model\Organization|null
     */
    public function getOrganization()
    {
        return $this->container['organization'];
    }

    /**
     * Sets organization
     *
     * @param \OpenAPI\FraudIntel\Client\Model\Organization|null $organization organization
     *
     * @return self
     */
    public function setOrganization($organization)
    {
        if (is_null($organization)) {
            throw new \InvalidArgumentException('non-nullable organization cannot be null');
        }
        $this->container['organization'] = $organization;

        return $this;
    }

    /**
     * Gets abuse_contact
     *
     * @return \OpenAPI\FraudIntel\Client\Model\AbuseContact|null
     */
    public function getAbuseContact()
    {
        return $this->container['abuse_contact'];
    }

    /**
     * Sets abuse_contact
     *
     * @param \OpenAPI\FraudIntel\Client\Model\AbuseContact|null $abuse_contact abuse_contact
     *
     * @return self
     */
    public function setAbuseContact($abuse_contact)
    {
        if (is_null($abuse_contact)) {
            throw new \InvalidArgumentException('non-nullable abuse_contact cannot be null');
        }
        $this->container['abuse_contact'] = $abuse_contact;

        return $this;
    }

    /**
     * Gets admin_contact
     *
     * @return \OpenAPI\FraudIntel\Client\Model\AdminContact|null
     */
    public function getAdminContact()
    {
        return $this->container['admin_contact'];
    }

    /**
     * Sets admin_contact
     *
     * @param \OpenAPI\FraudIntel\Client\Model\AdminContact|null $admin_contact admin_contact
     *
     * @return self
     */
    public function setAdminContact($admin_contact)
    {
        if (is_null($admin_contact)) {
            throw new \InvalidArgumentException('non-nullable admin_contact cannot be null');
        }
        $this->container['admin_contact'] = $admin_contact;

        return $this;
    }

    /**
     * Gets tech_contact
     *
     * @return \OpenAPI\FraudIntel\Client\Model\TechContact|null
     */
    public function getTechContact()
    {
        return $this->container['tech_contact'];
    }

    /**
     * Sets tech_contact
     *
     * @param \OpenAPI\FraudIntel\Client\Model\TechContact|null $tech_contact tech_contact
     *
     * @return self
     */
    public function setTechContact($tech_contact)
    {
        if (is_null($tech_contact)) {
            throw new \InvalidArgumentException('non-nullable tech_contact cannot be null');
        }
        $this->container['tech_contact'] = $tech_contact;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
